pos_demoji = [":1st_place_medal:",":2nd_place_medal:",":3rd_place_medal:", ":Christmas_tree:", ":OK_hand:", ":OK_hand_dark_skin_tone:",
":OK_hand_light_skin_tone:", ":OK_hand_medium-dark_skin_tone:", ":OK_hand_medium-light_skin_tone:", ":OK_hand_medium_skin_tone:",
":TOP_arrow:", ":backhand_index_pointing_up:", ":backhand_index_pointing_up_dark_skin_tone:", 
":backhand_index_pointing_up_light_skin_tone:", ":backhand_index_pointing_up_medium-dark_skin_tone:", 
":backhand_index_pointing_up_medium-light_skin_tone:", ":backhand_index_pointing_up_medium_skin_tone:", ":balloon:", ":beach_with_umbrella:",
":bikini:", ":birthday_cake:", ":black_heart:", ":blossom:", ":blue_heart:", ":bouquet:", ":butterfly:", ":candy:", ":cherries:", ":cherry_blossom:",
":couple_with_heart:", ":couple_with_heart_man_man:", ":couple_with_heart_woman_man:", ":couple_with_heart_woman_woman:",
":crossed_fingers:", ":crossed_fingers_dark_skin_tone:", ":crossed_fingers_light_skin_tone:", ":crossed_fingers_medium-dark_skin_tone:",
":crossed_fingers_medium-light_skin_tone:", ":crossed_fingers_medium_skin_tone:", ":drooling_face:", ":face_blowing_a_kiss:",
":face_savoring_food:", ":face_with_tears_of_joy:", ":face_with_tongue:", ":fireworks:", ":folded_hands:", ":folded_hands_dark_skin_tone:",
":folded_hands_light_skin_tone:", ":folded_hands_medium-dark_skin_tone:", ":folded_hands_medium-light_skin_tone:", ":folded_hands_medium_skin_tone:",
":growing_heart:", ":heart_decoration:", ":heart_suit:", ":heart_with_arrow:", ":heart_with_ribbon:", ":hugging_face:", ":ice_cream:",
":index_pointing_up:", ":index_pointing_up_dark_skin_tone:", ":index_pointing_up_light_skin_tone:", ":index_pointing_up_medium-dark_skin_tone:",
":index_pointing_up_medium-light_skin_tone:", ":index_pointing_up_medium_skin_tone:", ":kiss:", ":kiss_man_man:", ":kiss_mark:", ":kiss_woman_man:",
":kiss_woman_woman:", ":kissing_cat_face:", ":kissing_face:", ":kissing_face_with_closed_eyes:", ":kissing_face_with_smiling_eyes:",
":lollipop:", ":love-you_gesture:", ":love-you_gesture_dark_skin_tone:", ":love-you_gesture_light_skin_tone:", 
":love-you_gesture_medium-dark_skin_tone:", ":love-you_gesture_medium-light_skin_tone:", ":love-you_gesture_medium_skin_tone:", 
":love_hotel:", ":love_letter:", ":man_and_woman_holding_hands:", ":man_gesturing_OK:", ":man_gesturing_OK_dark_skin_tone:", 
":man_gesturing_OK_light_skin_tone:", ":man_gesturing_OK_medium-dark_skin_tone:", ":man_gesturing_OK_medium-light_skin_tone:", 
":man_gesturing_OK_medium_skin_tone:" ":nail_polish:", ":nail_polish_dark_skin_tone:", ":nail_polish_light_skin_tone:",
":nail_polish_medium-dark_skin_tone:", ":nail_polish_medium-light_skin_tone:", ":nail_polish_medium_skin_tone:", ":open_hands:", 
":open_hands_dark_skin_tone:", ":open_hands_light_skin_tone:", ":open_hands_medium-dark_skin_tone:", ":open_hands_medium-light_skin_tone:", 
":open_hands_medium_skin_tone:", ":palms_up_together:", ":palms_up_together_dark_skin_tone:", ":palms_up_together_light_skin_tone:",
":palms_up_together_medium-dark_skin_tone:", ":palms_up_together_medium-light_skin_tone:", ":palms_up_together_medium_skin_tone:",
":people_holding_hands:", ":person_gesturing_OK:", ":person_gesturing_OK_dark_skin_tone:", ":person_gesturing_OK_light_skin_tone:",
":person_gesturing_OK_medium-dark_skin_tone:", ":person_gesturing_OK_medium-light_skin_tone:", ":person_gesturing_OK_medium_skin_tone:",
":purple_heart:", ":red_heart:",":slightly_smiling_face:", ":smiling_cat_face_with_heart-eyes:", ":smiling_face:", ":smiling_face_with_halo:",
":smiling_face_with_3_hearts:", ":smiling_face_with_heart-eyes:", ":smiling_face_with_horns:", ":smiling_face_with_smiling_eyes:",
":smiling_face_with_sunglasses:", ":smirking_face:", ":sparkling_heart:", ":sun:", ":thumbs_up:", ":thumbs_up_dark_skin_tone:",
":thumbs_up_light_skin_tone:", ":thumbs_up_medium-dark_skin_tone:", ":thumbs_up_medium-light_skin_tone:", ":thumbs_up_medium_skin_tone:",
":white_heart:", ":woman_gesturing_OK:", ":woman_gesturing_OK_dark_skin_tone:", ":woman_gesturing_OK_light_skin_tone:",
":woman_gesturing_OK_medium-dark_skin_tone:", ":woman_gesturing_OK_medium-light_skin_tone:", ":woman_gesturing_OK_medium_skin_tone:",
":yellow_heart:"]



neg_demoji = [":SOS_button:", ":ambulance:", ":angry_face:", ":angry_face_with_horns:", ":anguished_face:", ":anxious_face_with_sweat:", 
":astonished_face:",":backhand_index_pointing_down:", ":backhand_index_pointing_down_dark_skin_tone:", 
":backhand_index_pointing_down_light_skin_tone:", ":backhand_index_pointing_down_medium-dark_skin_tone:", 
":backhand_index_pointing_down_medium-light_skin_tone:", ":backhand_index_pointing_down_medium_skin_tone:", ":broken_heart:", ":clown_face:",
":cold_face:", ":confounded_face:", ":confused_face:", ":crying_cat_face:", ":crying_face:", ":disappointed_face:", ":dizzy_face:",
":face_screaming_in_fear:", ":face_vomiting:", ":face_with_hand_over_mouth:", ":face_with_head-bandage:", ":face_with_open_mouth:",
":face_with_raised_eyebrow:", ":face_with_rolling_eyes:", ":face_with_steam_from_nose:", ":face_with_symbols_on_mouth:", ":face_with_thermometer:",
":face_with_monocle:", ":face_without_mouth:", ":fearful_face:", ":grimacing_face:", ":grinning_cat_face:", ":grinning_cat_face_with_smiling_eyes:",
":grinning_face:", ":grinning_face_with_big_eyes:", ":grinning_face_with_smiling_eyes:", ":grinning_face_with_sweat:", ":grinning_squinting_face:",
":hand_with_fingers_splayed:", ":hand_with_fingers_splayed_dark_skin_tone:", ":hand_with_fingers_splayed_light_skin_tone:",
":hand_with_fingers_splayed_medium-dark_skin_tone:", ":hand_with_fingers_splayed_medium-light_skin_tone:", 
":hand_with_fingers_splayed_medium_skin_tone:", ":loudly_crying_face:", ":man_facepalming:", ":man_facepalming_dark_skin_tone:",
":man_facepalming_light_skin_tone:", ":man_facepalming_medium-dark_skin_tone:", ":man_facepalming_medium-light_skin_tone:",
":man_facepalming_medium_skin_tone:", ":middle_finger:", ":middle_finger_dark_skin_tone:", ":man_gesturing_NO:", 
":man_gesturing_NO_dark_skin_tone:", ":woman_gesturing_NO_light_skin_tone:", ":man_gesturing_NO_medium-dark_skin_tone:", 
":man_gesturing_NO_medium-light_skin_tone:", ":man_gesturing_NO_medium_skin_tone:"
":middle_finger_light_skin_tone:", ":middle_finger_medium-dark_skin_tone:", ":middle_finger_medium-light_skin_tone:",
":middle_finger_medium_skin_tone:", ":pensive_face:", ":person_gesturing_NO:", ":person_gesturing_NO_dark_skin_tone:",
":person_gesturing_NO_light_skin_tone:", ":person_gesturing_NO_medium-dark_skin_tone:", ":person_gesturing_NO_medium-light_skin_tone:",
":person_gesturing_NO_medium_skin_tone:", ":pouting_cat_face:", ":pouting_face:", ":shushing_face:", ":sleeping_face:", ":sleepy_face:",
":slightly_frowning_face:", ":thumbs_down:", ":thumbs_down_dark_skin_tone:", ":thumbs_down_light_skin_tone:", ":thumbs_down_medium-dark_skin_tone:",
":thumbs_down_medium-light_skin_tone:", ":thumbs_down_medium_skin_tone:", ":woman_facepalming:", ":woman_facepalming_dark_skin_tone:",
":woman_facepalming_light_skin_tone:", ":woman_facepalming_medium-dark_skin_tone:", ":woman_facepalming_medium-light_skin_tone:",
":woman_facepalming_medium_skin_tone:", ":woman_gesturing_NO:", ":woman_gesturing_NO_dark_skin_tone:", ":woman_gesturing_NO_light_skin_tone:",
":woman_gesturing_NO_medium-dark_skin_tone:", ":woman_gesturing_NO_medium-light_skin_tone:", ":woman_gesturing_NO_medium_skin_tone:", 
":yawning_face:"]

